// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2IRO7W8jnH8sgGhGIpXWdKlOdZlw_Oos',
    appId: '1:100873353123:web:d0f6a34e55fa06130f8c16',
    messagingSenderId: '100873353123',
    projectId: 'bookapp-753fb',
    authDomain: 'bookapp-753fb.firebaseapp.com',
    storageBucket: 'bookapp-753fb.firebasestorage.app',
    measurementId: 'G-1YWBGDP7VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOp5kU8-YpAiDdR69oLiuyIY4pBwQPrQo',
    appId: '1:100873353123:android:4016f8edeba219890f8c16',
    messagingSenderId: '100873353123',
    projectId: 'bookapp-753fb',
    storageBucket: 'bookapp-753fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79zR94VY0fowXPJjQ5WTQe8Nwc6ronv4',
    appId: '1:100873353123:ios:4e794798723e881f0f8c16',
    messagingSenderId: '100873353123',
    projectId: 'bookapp-753fb',
    storageBucket: 'bookapp-753fb.firebasestorage.app',
    androidClientId: '100873353123-mfr14g45omghpge2c0p2gpqusvuc2i32.apps.googleusercontent.com',
    iosClientId: '100873353123-p8f65c30mffvrel2g20j1gt9ctrk62dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB79zR94VY0fowXPJjQ5WTQe8Nwc6ronv4',
    appId: '1:100873353123:ios:4e794798723e881f0f8c16',
    messagingSenderId: '100873353123',
    projectId: 'bookapp-753fb',
    storageBucket: 'bookapp-753fb.firebasestorage.app',
    androidClientId: '100873353123-mfr14g45omghpge2c0p2gpqusvuc2i32.apps.googleusercontent.com',
    iosClientId: '100873353123-p8f65c30mffvrel2g20j1gt9ctrk62dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2IRO7W8jnH8sgGhGIpXWdKlOdZlw_Oos',
    appId: '1:100873353123:web:4197afe4ef1490fa0f8c16',
    messagingSenderId: '100873353123',
    projectId: 'bookapp-753fb',
    authDomain: 'bookapp-753fb.firebaseapp.com',
    storageBucket: 'bookapp-753fb.firebasestorage.app',
    measurementId: 'G-6VEZEQYNRQ',
  );

}